############# Portuguese navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

#[[main]]
#name = "Sobre"
#url = "/sobre"
#weight = 2

# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

[[main]]
name = "Eventos"
url = "/eventos"
weight = 2

#[[main]]
#name = "Contato"
#url = "/contato"
# weight = 3

[[main]]
name = "Organizadoras"
url = "/organizadoras"
weight = 3

# [[main]]
# name = "Categories"
# url = "/categories"
# weight = 3

# [[main]]
# name = "404 Page"
#url = "/404"
# weight = 3


# footer menu
[[footer]]
name = "Sobre"
url = "/sobre"
weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
